import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models.dart';

class PdfGenerator {
  static Future<void> generateVehicleReport(
    Vehicle vehicle,
    List<MaintenanceLog> logs,
  ) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat.yMMMd();
    final currencyFormat = NumberFormat.currency(symbol: '\$');
    final numberFormat = NumberFormat('#,###');

    // Calculate totals
    double totalCost = 0;
    for (var log in logs) {
      totalCost += log.cost;
    }

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.letter,
        build: (pw.Context context) {
          return [
            // Header
            pw.Header(
              level: 0,
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'Vehicle Maintenance Report',
                    style: pw.TextStyle(
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 8),
                  pw.Text(
                    '${vehicle.year} ${vehicle.make} ${vehicle.model}',
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.grey700,
                    ),
                  ),
                  pw.Text(
                    'VIN: ${(vehicle.vin == null || vehicle.vin!.isEmpty) ? "N/A" : vehicle.vin}',
                    style: const pw.TextStyle(fontSize: 12),
                  ),
                  pw.Text(
                    'Generated on: ${dateFormat.format(DateTime.now())}',
                    style: const pw.TextStyle(fontSize: 12),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // Cost Summary
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(5)),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Total Services', style: const pw.TextStyle(color: PdfColors.grey600)),
                      pw.Text('${logs.length}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16)),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Total Cost', style: const pw.TextStyle(color: PdfColors.grey600)),
                      pw.Text(currencyFormat.format(totalCost), style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 16, color: PdfColors.green700)),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 20),

            // Maintenance Table
            pw.Text(
              'Maintenance History',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 10),
            pw.Table.fromTextArray(
              context: context,
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.grey200,
              ),
              headerHeight: 25,
              cellHeight: 30,
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.centerLeft,
                2: pw.Alignment.centerRight,
                3: pw.Alignment.centerRight,
              },
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              headers: ['Date', 'Service', 'Mileage', 'Cost'],
              data: logs.map((log) {
                return [
                  dateFormat.format(log.date),
                  log.type.label,
                  numberFormat.format(log.mileage),
                  currencyFormat.format(log.cost),
                ];
              }).toList(),
            ),
            
            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.Padding(
                padding: const pw.EdgeInsets.only(top: 10),
                child: pw.Text("Generated by Vehicle Tracker App", style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500))
            ),
          ];
        },
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(), 
      filename: 'report_${vehicle.nickname.replaceAll(' ', '_')}.pdf',
    );
  }
}
